### ISSUE TITLE
tf.summary.FileWriter

### ISSUE THREAD

**Issue by dklingmann** [CUHKSZ-TQL/EverybodyDanceNow_reproduce_pytorch#99]
https://github.com/yanx27/EverybodyDanceNow_reproduce_pytorch/blob/a740351bc422a5322339d3bcee2fb25510a01a19/src/pix2pixHD/util/visualizer.py#L26

Please note that tf.summary.FileWriter is deprecated. Instead, tf.compat.v1.summary.FileWriter can be used. Alternatively, tensorflow version 1.x should be used.

**Comment by ghost** [comment]
@dklingmann do you know by any chance how to fix this issue: https://github.com/yanx27/EverybodyDanceNow_reproduce_pytorch/issues/102 ?
It seems similar to this one

P.S. I changed it to `tf.summary.create_file_writer`, as said in the error message, and for now I'm not getting this error (it's currently executing this sell)
